/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import entidade.EDiscente;
import java.util.Vector;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.NDiscente;
import persistencia.PDiscente;

/**
 *
 * @author Pedro
 */
public class APesquisaDiscente extends javax.swing.JInternalFrame {

    JDesktopPane jDesktopPanePrincipal;

    /**
     * Creates new form Pesquisar_Discente
     */
    public APesquisaDiscente() {
        initComponents();
        preencherTela();
    }

    public APesquisaDiscente(JDesktopPane jDesktopPanePrincipal) {
        this();

        this.jDesktopPanePrincipal = jDesktopPanePrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonFechar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePesquisar = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Pesquisar Discente");

        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jTablePesquisar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTablePesquisarMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTablePesquisar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(596, Short.MAX_VALUE)
                .addComponent(jButtonFechar)
                .addGap(37, 37, 37))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFechar)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        try {
            dispose();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jTablePesquisarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePesquisarMousePressed
        try {
            int linha = jTablePesquisar.getSelectedRow();
            String matricula = jTablePesquisar.getValueAt(linha,0).toString();
            
            EDiscente discente = new NDiscente().consultar(Integer.parseInt(matricula));
                    
            ACadastroDiscente tela04 =  new ACadastroDiscente(jDesktopPanePrincipal, discente);
            jDesktopPanePrincipal.add(tela04);
            tela04.setVisible(true);
            
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jTablePesquisarMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablePesquisar;
    // End of variables declaration//GEN-END:variables
    public void preencherTela() {
        try {
            //criando  o cabecalho da tabela
            Vector<String> cabecalho = new Vector();
            cabecalho.add("MATRICULA");
            cabecalho.add("CPF");
            cabecalho.add("NOME");
            cabecalho.add("NOMEPAI");
            cabecalho.add("NOMEMAE");
            cabecalho.add("DATADENASCIMENTO");
            cabecalho.add("TELEFONE");
            cabecalho.add("CELULAR");
            cabecalho.add("EMAIL");
            cabecalho.add("ENDERECO");
            cabecalho.add("SEXO");

            Vector detalhes = new Vector();
            for (EDiscente detalhe : new PDiscente().listar()) {
                //criando  linha da tabela
                Vector<String> linha = new Vector();
                linha.add(detalhe.getMatricula() + "");
                linha.add(detalhe.getCPF());
                linha.add(detalhe.getNome());
                linha.add(detalhe.getNomePai());
                linha.add(detalhe.getNomeMae());
                linha.add(detalhe.getDataNascimento());
                linha.add(detalhe.getTelefone());
                linha.add(detalhe.getCelular());
                linha.add(detalhe.getEmail());
                linha.add(detalhe.getEndereco());
                linha.add(detalhe.getSexo().toString());
                detalhes.add(linha);
            }
            jTablePesquisar.setModel(new DefaultTableModel(detalhes, cabecalho));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
}
