/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;


import entidade.EDiscente;
import java.util.Vector;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.PDiscente;

/**
 *
 * @author Pedro
 */
public class Discente_Pesquisar extends javax.swing.JInternalFrame {
    JDesktopPane jDesktopPanePrincipal;
    /**
     * Creates new form Pesquisar_Discente
     */
    public Discente_Pesquisar() {
        initComponents();
    }
    public Discente_Pesquisar(JDesktopPane jDesktopPanePrincipal){
        this();
        
        this.jDesktopPanePrincipal = jDesktopPanePrincipal;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisar = new javax.swing.JTable();
        jButtonFechar = new javax.swing.JButton();

        setResizable(true);
        setTitle("Pesquisar Discente");

        jTablePesquisar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTablePesquisar);

        jButtonFechar.setText("Fechar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFechar)
                .addGap(37, 37, 37))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFechar)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePesquisar;
    // End of variables declaration//GEN-END:variables
    public void preencherTela(){
        try {
            //criando  o cabecalho da tabela
            Vector<String> cabecalho = new Vector();
            cabecalho.add("MATRICULA");
            cabecalho.add("CPF");
            cabecalho.add("NOME");
            cabecalho.add("NOMEPAI");
            cabecalho.add("NOMEMAE");
            cabecalho.add("DATADENASCIMENTO");
            cabecalho.add("TELEFONE");
            cabecalho.add("EMAIL");
            cabecalho.add("ENDERECO");
            cabecalho.add("SEXO");
            
            Vector detalhes = new Vector();
            for(EDiscente detalhe : new PDiscente().listar()){
                //criando  linha da tabela
                Vector<String> linha = new Vector();
                linha.add(detalhe.getMatricula()+ "");
                linha.add(detalhe.getCPF()) ;
                linha.add(detalhe.getCelular());
                linha.add(detalhe.getDataNascimento());
                linha.add(detalhe.getEmail());
                linha.add(detalhe.getEndereco());
                linha.add(detalhe.getNome());
                linha.add(detalhe.getNomeMae());
                linha.add(detalhe.getNomePai());
                linha.add(detalhe.getTelefone()+ "");
                linha.add(detalhe.getSexo().toString());
                detalhes.add(linha);
            }
            jTablePesquisar.setModel(new DefaultTableModel(detalhes, cabecalho));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
}
